# Generated by Django 3.0.8 on 2020-08-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200811_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('commented_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Entry')),
                ('notification_maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
