# Generated by Django 2.2.3 on 2020-03-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_followersandfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='followed_by', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='following_to', to='users.UserProfile'),
        ),
        migrations.DeleteModel(
            name='FollowersAndFollowing',
        ),
    ]
