# Generated by Django 2.2.3 on 2020-03-13 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200304_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
