# Generated by Django 2.2.3 on 2020-05-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_date',
        ),
    ]
