# Generated by Django 2.2.3 on 2020-07-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0007_auto_20200523_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeSystem_dislikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliker', to=settings.AUTH_USER_MODEL)),
                ('likeSystem_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.Entry')),
                ('likeSystem_likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'likeSystems',
            },
        ),
    ]
