# Generated by Django 2.2.3 on 2020-07-22 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0008_likesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeSystem',
        ),
    ]
